---
- name: handler test
  hosts: all
  tasks:
    - name: excute ls
      shell: ls
      notify:
        - stop message taskname=ls

    - name: status sshd
      shell: systemctl status sshd
      notify:
        - stop message taskname=sshd

  handlers:
    - name: stop message
      debug:
        msg: "stop {{ taskname }} task"
