---
- name: loop test
  hosts: 192.168.0.184
  gather_facts: False
  tasks:
  - debug: 
      msg: "{{ item }}"
    loop:
    - a
    - b
    - c
    

  - name: add server user
    user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.group }}"
    loop:
      - { name: "worker1", group: "worker" }
      - { name: "worker2", group: "worker" }
      - { name: "worker3", group: "ansible" }
