---
- name: loop test
  hosts: 192.168.0.184
  gather_facts: False
  tasks:
  - debug: 
      msg: "{{ item }}"
    loop:
    - a
    - b
    - c
    

  - name: add server user
    user:
      name: "{{ item }}"
      state: present
      groups: worker
    loop:
      - worker1
      - worker2
      - worker3
      