---
- name: sample playbook
  hosts: target
  vars:
    hue_rul: "https://cdn.gethue.com/downloads/hue-4.10.0.tgz"
    dest_dir: /tmp
    file_name: hue-4.10.0
  vars_file:
    - variable
  tasks:
    # task
          - name: download hue file # 설명을 위한 식별자
            # 모듈
            get_url:
                    url: "{{ hue_url }}"
                    dest: "{{ dest_dir }}"
                    mode: '0660'

          - name: unarchive hue file
            unarchive: 
                    src: "{{ dest_dir }}/{{ file_name }}"
                    dest: "{{ dest_dir }}/{{ file_name }}"
                    remote_src: True
                    owner: hue
                    group: hue

          - name: create symlink /opt/hue
            file: 
                    src: "{{ dest_dir }}/{{ file_name }}"
                    dest: "{{ dest_dir }}/hue"
                    state: link
                    owner: hue
                    group: hue
