---
- name: ping test
  hosts: target
  gather_facts: True
  #remote_user: root
  tasks:
  - name: ping test
    ping:

- name: touch file test
  hosts: target
  remote_user: root
  gather_facts: false
  tasks:
  - name: create directory
    file:
      path: /home/worker/test
      state: directory

  - name: touch file
    file:
      path: /home/worker/test/test.txt
      state: touch